/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankLedgerRouteImport } from './routes/bank-ledger'
import { Route as BillWisePurchaseRouteImport } from './routes/bill-wise-purchase'
import { Route as BillWiseSalesRouteImport } from './routes/bill-wise-sales'
import { Route as BillsSalesRouteImport } from './routes/bills-sales'
import { Route as CashItParkRouteImport } from './routes/cash-it-park'
import { Route as CashMahidharpuraRouteImport } from './routes/cash-mahidharpura'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as ExpenseLedgerRouteImport } from './routes/expense-ledger'
import { Route as PnlRouteImport } from './routes/pnl'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as UchhinaRouteImport } from './routes/uchhina'
import { Route as UnlockRouteImport } from './routes/unlock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankLedgerRoute = BankLedgerRouteImport.update({
  id: '/bank-ledger',
  path: '/bank-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const BillWisePurchaseRoute = BillWisePurchaseRouteImport.update({
  id: '/bill-wise-purchase',
  path: '/bill-wise-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const BillWiseSalesRoute = BillWiseSalesRouteImport.update({
  id: '/bill-wise-sales',
  path: '/bill-wise-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsSalesRoute = BillsSalesRouteImport.update({
  id: '/bills-sales',
  path: '/bills-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const CashItParkRoute = CashItParkRouteImport.update({
  id: '/cash-it-park',
  path: '/cash-it-park',
  getParentRoute: () => rootRouteImport,
} as any)
const CashMahidharpuraRoute = CashMahidharpuraRouteImport.update({
  id: '/cash-mahidharpura',
  path: '/cash-mahidharpura',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseLedgerRoute = ExpenseLedgerRouteImport.update({
  id: '/expense-ledger',
  path: '/expense-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlRoute = PnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const UchhinaRoute = UchhinaRouteImport.update({
  id: '/uchhina',
  path: '/uchhina',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-ledger': typeof BankLedgerRoute
  '/bill-wise-purchase': typeof BillWisePurchaseRoute
  '/bill-wise-sales': typeof BillWiseSalesRoute
  '/bills-sales': typeof BillsSalesRoute
  '/cash-it-park': typeof CashItParkRoute
  '/cash-mahidharpura': typeof CashMahidharpuraRoute
  '/drawings': typeof DrawingsRoute
  '/expense-ledger': typeof ExpenseLedgerRoute
  '/pnl': typeof PnlRoute
  '/purchase': typeof PurchaseRoute
  '/sales': typeof SalesRoute
  '/tax': typeof TaxRoute
  '/uchhina': typeof UchhinaRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-ledger': typeof BankLedgerRoute
  '/bill-wise-purchase': typeof BillWisePurchaseRoute
  '/bill-wise-sales': typeof BillWiseSalesRoute
  '/bills-sales': typeof BillsSalesRoute
  '/cash-it-park': typeof CashItParkRoute
  '/cash-mahidharpura': typeof CashMahidharpuraRoute
  '/drawings': typeof DrawingsRoute
  '/expense-ledger': typeof ExpenseLedgerRoute
  '/pnl': typeof PnlRoute
  '/purchase': typeof PurchaseRoute
  '/sales': typeof SalesRoute
  '/tax': typeof TaxRoute
  '/uchhina': typeof UchhinaRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-ledger': typeof BankLedgerRoute
  '/bill-wise-purchase': typeof BillWisePurchaseRoute
  '/bill-wise-sales': typeof BillWiseSalesRoute
  '/bills-sales': typeof BillsSalesRoute
  '/cash-it-park': typeof CashItParkRoute
  '/cash-mahidharpura': typeof CashMahidharpuraRoute
  '/drawings': typeof DrawingsRoute
  '/expense-ledger': typeof ExpenseLedgerRoute
  '/pnl': typeof PnlRoute
  '/purchase': typeof PurchaseRoute
  '/sales': typeof SalesRoute
  '/tax': typeof TaxRoute
  '/uchhina': typeof UchhinaRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank-ledger'
    | '/bill-wise-purchase'
    | '/bill-wise-sales'
    | '/bills-sales'
    | '/cash-it-park'
    | '/cash-mahidharpura'
    | '/drawings'
    | '/expense-ledger'
    | '/pnl'
    | '/purchase'
    | '/sales'
    | '/tax'
    | '/uchhina'
    | '/unlock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank-ledger'
    | '/bill-wise-purchase'
    | '/bill-wise-sales'
    | '/bills-sales'
    | '/cash-it-park'
    | '/cash-mahidharpura'
    | '/drawings'
    | '/expense-ledger'
    | '/pnl'
    | '/purchase'
    | '/sales'
    | '/tax'
    | '/uchhina'
    | '/unlock'
  id:
    | '__root__'
    | '/'
    | '/bank-ledger'
    | '/bill-wise-purchase'
    | '/bill-wise-sales'
    | '/bills-sales'
    | '/cash-it-park'
    | '/cash-mahidharpura'
    | '/drawings'
    | '/expense-ledger'
    | '/pnl'
    | '/purchase'
    | '/sales'
    | '/tax'
    | '/uchhina'
    | '/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankLedgerRoute: typeof BankLedgerRoute
  BillWisePurchaseRoute: typeof BillWisePurchaseRoute
  BillWiseSalesRoute: typeof BillWiseSalesRoute
  BillsSalesRoute: typeof BillsSalesRoute
  CashItParkRoute: typeof CashItParkRoute
  CashMahidharpuraRoute: typeof CashMahidharpuraRoute
  DrawingsRoute: typeof DrawingsRoute
  ExpenseLedgerRoute: typeof ExpenseLedgerRoute
  PnlRoute: typeof PnlRoute
  PurchaseRoute: typeof PurchaseRoute
  SalesRoute: typeof SalesRoute
  TaxRoute: typeof TaxRoute
  UchhinaRoute: typeof UchhinaRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-ledger': {
      id: '/bank-ledger'
      path: '/bank-ledger'
      fullPath: '/bank-ledger'
      preLoaderRoute: typeof BankLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-wise-purchase': {
      id: '/bill-wise-purchase'
      path: '/bill-wise-purchase'
      fullPath: '/bill-wise-purchase'
      preLoaderRoute: typeof BillWisePurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-wise-sales': {
      id: '/bill-wise-sales'
      path: '/bill-wise-sales'
      fullPath: '/bill-wise-sales'
      preLoaderRoute: typeof BillWiseSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills-sales': {
      id: '/bills-sales'
      path: '/bills-sales'
      fullPath: '/bills-sales'
      preLoaderRoute: typeof BillsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-it-park': {
      id: '/cash-it-park'
      path: '/cash-it-park'
      fullPath: '/cash-it-park'
      preLoaderRoute: typeof CashItParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-mahidharpura': {
      id: '/cash-mahidharpura'
      path: '/cash-mahidharpura'
      fullPath: '/cash-mahidharpura'
      preLoaderRoute: typeof CashMahidharpuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense-ledger': {
      id: '/expense-ledger'
      path: '/expense-ledger'
      fullPath: '/expense-ledger'
      preLoaderRoute: typeof ExpenseLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl': {
      id: '/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof PnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uchhina': {
      id: '/uchhina'
      path: '/uchhina'
      fullPath: '/uchhina'
      preLoaderRoute: typeof UchhinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankLedgerRoute: BankLedgerRoute,
  BillWisePurchaseRoute: BillWisePurchaseRoute,
  BillWiseSalesRoute: BillWiseSalesRoute,
  BillsSalesRoute: BillsSalesRoute,
  CashItParkRoute: CashItParkRoute,
  CashMahidharpuraRoute: CashMahidharpuraRoute,
  DrawingsRoute: DrawingsRoute,
  ExpenseLedgerRoute: ExpenseLedgerRoute,
  PnlRoute: PnlRoute,
  PurchaseRoute: PurchaseRoute,
  SalesRoute: SalesRoute,
  TaxRoute: TaxRoute,
  UchhinaRoute: UchhinaRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
